---
- name: Build base container image from Dockerfile
  hosts: dev
  gather_facts: false
  vars:
    gitlab_dir: "/home/{{ ansible_user }}/gitlab"
  tasks:

   - name: Copy gitlab Dockerfile to hosts
     ansible.builtin.template:
       src: templates/gitlab_dockerfile.j2
       dest: "{{ gitlab_dir }}/Dockerfile"
       mode: '0755'

   - name: Build gitlab
     community.docker.docker_image:
       build:
         path: "{{ gitlab_dir }}"
       name: gitlab
       state: present
       source: build
       force_source: true
       tag: "{{ tag | default('latest') }}"

   - name: Run gitlab
     ansible.builtin.shell: docker run --detach \
            --hostname gitlab \
            --name gitlab \
            --publish 8080:80 --publish 2222:22 \
            --restart always \
            --volume {{ gitlab_dir }}/config:/etc/gitlab \
            --volume {{ gitlab_dir }}/logs:/var/log/gitlab \
            --volume {{ gitlab_dir }}/data:/var/opt/gitlab \
            --shm-size 256m \
            --network staging_network
            gitlab
...