---
- name: Sets up Gitlab via Docker
  hosts: dev
  vars:
    gitlab_dir: "/home/{{ ansible_user }}/gitlab"

  tasks:
   - name: Create gitlab dir
     ansible.builtin.file:
       path: "{{ gitlab_dir }}"
       state: directory
       mode: '0755'

   - name: Create gitlab sub-dirs
     ansible.builtin.file:
       path: "{{ gitlab_dir }}/{{ item }}"
       mode: '0755'
       state: directory
     loop:
       - config
       - logs
       - data
...