---
- name: Build MariaDB on Docker
  hosts: dev
  vars:
    mariadb_dir: "/home/{{ ansible_user }}/mariadb"
    mariadb_vol: "{{ mariadb_dir }}/database"
  vars_files:
    - secrets.yml

  tasks:
    - name: Create directory for mariadb volume
      ansible.builtin.file:
        path: "{{ mariadb_vol }}"
        state: directory
        mode: '0755'

    - name: Copy MariaDB Dockerfile to host
      ansible.builtin.template:
        src: templates/mariadb_dockerfile.j2
        dest: "{{ mariadb_dir }}/Dockerfile"
        mode: '0755'

    - name: Build Mariadb
      community.docker.docker_image:
        build:
          path: "{{ mariadb_dir }}"
        name: mariadb_staging
        state: present
        source: build
        force_source: true
        tag: "{{ tag | default('latest') }}"

    - name: Run MariaDB
      community.docker.docker_container:
        hostname: mariadb
        name: mariadb_staging
        networks:
          - name: staging_network
        published_ports:
          - 3306
        mounts:
          - source: "{{ mariadb_vol }}"
            target: /var/lib/mysql
            type: bind
        restart_policy: on-failure
        image: mariadb_staging
        state: started
...
