---
- name: Tear down Docker containers
  hosts: dev
  vars:
    db: mariad_staging
    web: wordpress_staging
    gitlab: gitlab_staging

  tasks:

    - name: Stop wordpress
      community.docker.docker_container:
        state: absent
        name: "{{ web }}"

    - name: Stop mariadb
      community.docker.docker_container:
        state: absent
        name: "{{ db }}"

    - name: Remove wordpress
      community.docker.docker_image:
        state: absent
        name: "{{ web }}"

    - name: Remove mariadb
      community.docker.docker_image:
        state: absent
        name: "{{ db }}"

    - name: Remove gitlab
      community.docker.docker_image:
        state: absent
        name: "{{ gitlab }}"
...
