---
- name: Build Wordpress on Docker
  hosts: dev
  vars:
    wordpress_dir: "/home/{{ ansible_user }}/wordpress"
  vars_files:
    - secrets.yml

  tasks:
    - name: Create directory for Wordpress
      ansible.builtin.file:
        path: "{{ wordpress_dir }}"
        state: directory
        mode: '0755'

    - name: Copy Wordpress Dockerfile to host
      ansible.builtin.template:
        src: templates/wordpress_dockerfile.j2
        dest: "{{ wordpress_dir }}/Dockerfile"
        mode: '0755'

    - name: Build Wordpress
      community.docker.docker_image:
        build:
          path: "{{ wordpress_dir }}"
        name: wordpress_staging
        state: present
        source: build
        force_source: true
        tag: "{{ tag | default('latest') }}"

    - name: Run Wordpress
      community.docker.docker_container:
        hostname: wordpress
        name: wordpress_staging
        networks:
          - name: staging_network
        published_ports:
          - 80:80
        restart_policy: on-failure
        image: wordpress_staging
        state: started
...
